In [2]:
import numpy as np

In [3]:
np_arr = np.arange(1000000)

In [4]:
py_list = list(range(1000000))

In [5]:
%time for _ in range(10): np_arr2 = np_arr * 2

CPU times: user 16 ms, sys: 7.06 ms, total: 23.1 ms
Wall time: 26.4 ms


In [6]:
%time for _ in range(10): py_list2 = py_list * 2

CPU times: user 193 ms, sys: 28.1 ms, total: 221 ms
Wall time: 227 ms


In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[-1.67567683, -0.4457551 , -0.2425788 ],
       [-0.3063904 , -2.28655655, -0.95580664]])

In [9]:
data * 10

array([[-16.75676826,  -4.45755103,  -2.42578802],
       [ -3.06390403, -22.86556548,  -9.55806642]])

In [10]:
data + data

array([[-3.35135365, -0.89151021, -0.4851576 ],
       [-0.61278081, -4.5731131 , -1.91161328]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [17]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int64')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.empty((2, 3, 2))

array([[[5.15168810e-316, 0.00000000e+000],
        [8.06809200e-321, 5.15354302e-316],
        [6.94802416e-310, 6.94802416e-310]],

       [[6.94802416e-310, 6.94802416e-310],
        [5.15167862e-316, 1.48219694e-323],
        [2.12199579e-314, 4.44659081e-323]]])

In [37]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [39]:
arr1.dtype

dtype('float64')

In [40]:
arr2.dtype

dtype('int32')

In [41]:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr.dtype

dtype('int64')

In [43]:
float_arr = arr.astype(np.float64)

In [44]:
float_arr.dtype

dtype('float64')

In [51]:
arr = np.array([3.4, -1.2, -2.5, 0.3, 12.4, 10.1])

In [52]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]],dtype=np.float64)

In [58]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [59]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [60]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [62]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [63]:
arr2 = np.array([[0., 4., 1.], [7.,2., 12.]])

In [64]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [65]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])